from .submarine import create_submarine
from .warship import create_warship
from .volcano import create_volcano
from .fish import create_fish
from .shark import create_shark
from .torpedo import create_torpedo
from .mine import create_mine
from .seaweed import create_seaweed
from .whale import create_whale
from .lighthouse import create_lighthouse
from .lawn import create_lawn
from .soil import create_soil
